### ISSUE TITLE
Java JRE edition - number of CPU´s (maximum)

### ISSUE THREAD

**Issue by yellow-panther** [frankkopp/FrankyUCIChessEngine#1]
Hello Frank,

which Java JRE version (8-9-10-11) is required to run Franky on Windows 7 SP1 32& 64 operation system?

Can you tell me please the maximum number of cores (CPU´s)  that are supported by your application ?

Last not least:  Is Chessly an engine with UCI or XBoard/WinBoard protocol too?

Regards,

**Comment by frankkopp** [comment]
Hi, 

it is developed with Java level 1.8. Should run on any JRE from 1.8 or higher.
Currently the engine does not use multiple CPU/cores. That's planned for a future version. 

Chessly has it's own UI and does not use UCI. I thought about extending it some day if my time allows it :)

Cheers
Frank
